# Generated by Django 5.2.7 on 2026-06-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CicloLectivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Ciclo Lectivo",
                "verbose_name_plural": "Ciclos Lectivos",
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="Acta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ORD", "Ordinaria"), ("EXT", "Extraordinaria")],
                        max_length=3,
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("mes", models.CharField(max_length=20)),
                ("contenido_md", models.TextField(blank=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="private/digesto/actas/"
                    ),
                ),
                (
                    "referencias",
                    models.ManyToManyField(
                        blank=True, related_name="referenciada_por", to="digesto.acta"
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actas",
                        to="digesto.ciclolectivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta",
                "verbose_name_plural": "Actas",
                "ordering": ["-ciclo__anio", "-numero"],
                "unique_together": {("ciclo", "tipo", "numero")},
            },
        ),
        migrations.CreateModel(
            name="Certificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("texto", models.TextField()),
                (
                    "acta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificaciones",
                        to="digesto.acta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificación",
                "verbose_name_plural": "Certificaciones",
                "ordering": ["acta__ciclo__anio", "acta__numero", "numero"],
                "unique_together": {("acta", "numero")},
            },
        ),
        migrations.CreateModel(
            name="Disposicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("texto", models.TextField()),
                (
                    "acta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposiciones",
                        to="digesto.acta",
                    ),
                ),
                (
                    "deroga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derogada_por",
                        to="digesto.disposicion",
                    ),
                ),
                (
                    "modifica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modificada_por",
                        to="digesto.disposicion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disposición",
                "verbose_name_plural": "Disposiciones",
                "ordering": ["acta__ciclo__anio", "acta__numero", "numero"],
                "unique_together": {("acta", "numero")},
            },
        ),
    ]
