# Generated by Django 5.2.6 on 2025-09-29 18:32

import django.db.models.deletion
import django.utils.timezone
import equivalencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planta_docente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                (
                    "email_estudiante",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "dni_pasaporte",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="DNI o Pasaporte",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AsignaturaParaEquivalencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignatura",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planta_docente.asignatura",
                        verbose_name="Asignatura",
                    ),
                ),
                (
                    "docente_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="planta_docente.docente",
                        verbose_name="Docente Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignatura para Equivalencia",
                "verbose_name_plural": "Asignaturas para Equivalencias",
            },
        ),
        migrations.CreateModel(
            name="SolicitudEquivalencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado_general",
                    models.CharField(
                        choices=[
                            ("En Proceso", "En Proceso"),
                            ("Completada", "Completada"),
                            ("Cancelada", "Cancelada"),
                        ],
                        default="En Proceso",
                        max_length=20,
                    ),
                ),
                (
                    "acta_firmada",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=equivalencias.models.get_equivalencias_upload_path,
                    ),
                ),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                (
                    "id_estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equivalencias.estudiante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoAdjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=equivalencias.models.get_equivalencias_upload_path
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equivalencias.solicitudequivalencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetalleSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_asignatura",
                    models.CharField(
                        choices=[
                            ("Pendiente de envío", "Pendiente de envío"),
                            ("Enviada a Cátedra", "Enviada a Cátedra"),
                            ("Aprobada", "Aprobada"),
                            ("Denegada", "Denegada"),
                            ("Requiere PC", "Requiere Programa Complementario"),
                        ],
                        default="Pendiente de envío",
                        max_length=20,
                    ),
                ),
                (
                    "detalle_pc",
                    models.TextField(
                        blank=True,
                        help_text="Detallar temas del Programa Complementario",
                        null=True,
                    ),
                ),
                ("fecha_dictamen", models.DateTimeField(blank=True, null=True)),
                (
                    "id_asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equivalencias.asignaturaparaequivalencia",
                    ),
                ),
                (
                    "id_solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equivalencias.solicitudequivalencia",
                    ),
                ),
            ],
        ),
    ]
