# Generated by Django 5.2.6 on 2025-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equivalencias", "0001_initial"),
        (
            "planta_docente",
            "0004_alter_correo_options_asignatura_asig_nivel_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detallesolicitud",
            options={
                "verbose_name": "Detalle de Solicitud",
                "verbose_name_plural": "Detalles de Solicitudes",
            },
        ),
        migrations.AlterModelOptions(
            name="documentoadjunto",
            options={
                "verbose_name": "Documento Adjunto",
                "verbose_name_plural": "Documentos Adjuntos",
            },
        ),
        migrations.AlterModelOptions(
            name="estudiante",
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitudequivalencia",
            options={
                "verbose_name": "Solicitud de Equivalencia",
                "verbose_name_plural": "Solicitudes de Equivalencia",
            },
        ),
        migrations.AddIndex(
            model_name="asignaturaparaequivalencia",
            index=models.Index(fields=["asignatura"], name="asig_equiv_asig_idx"),
        ),
        migrations.AddIndex(
            model_name="asignaturaparaequivalencia",
            index=models.Index(
                fields=["docente_responsable"], name="asig_equiv_doc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detallesolicitud",
            index=models.Index(fields=["id_solicitud"], name="det_solicitud_idx"),
        ),
        migrations.AddIndex(
            model_name="detallesolicitud",
            index=models.Index(fields=["id_asignatura"], name="det_asignatura_idx"),
        ),
        migrations.AddIndex(
            model_name="detallesolicitud",
            index=models.Index(fields=["estado_asignatura"], name="det_estado_idx"),
        ),
        migrations.AddIndex(
            model_name="detallesolicitud",
            index=models.Index(
                fields=["id_solicitud", "estado_asignatura"], name="det_sol_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentoadjunto",
            index=models.Index(fields=["solicitud"], name="doc_solicitud_idx"),
        ),
        migrations.AddIndex(
            model_name="estudiante",
            index=models.Index(fields=["dni_pasaporte"], name="est_dni_idx"),
        ),
        migrations.AddIndex(
            model_name="estudiante",
            index=models.Index(fields=["nombre_completo"], name="est_nombre_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitudequivalencia",
            index=models.Index(fields=["id_estudiante"], name="sol_estudiante_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitudequivalencia",
            index=models.Index(fields=["estado_general"], name="sol_estado_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitudequivalencia",
            index=models.Index(fields=["fecha_inicio"], name="sol_fecha_inicio_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitudequivalencia",
            index=models.Index(fields=["fecha_completada"], name="sol_fecha_comp_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitudequivalencia",
            index=models.Index(
                fields=["estado_general", "fecha_inicio"], name="sol_estado_fecha_idx"
            ),
        ),
    ]
