# Generated by Django 5.2.7 on 2026-03-20 19:26

import equivalencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equivalencias", "0002_alter_detallesolicitud_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoadjunto",
            name="fecha_subida",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentoadjunto",
            name="archivo",
            field=models.FileField(
                upload_to=equivalencias.models.get_equivalencias_upload_path,
                validators=[
                    equivalencias.models.validate_file_extension,
                    equivalencias.models.validate_file_size,
                ],
            ),
        ),
    ]
