# Generated by Django 5.2.7 on 2026-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equivalencias", "0003_agregar_validadores_archivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionDepartamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firma_imagen",
                    models.ImageField(
                        upload_to="firmas/", verbose_name="Imagen de firma"
                    ),
                ),
                ("nombre_firmante", models.CharField(max_length=200)),
                ("cargo_firmante", models.CharField(max_length=200)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuración del Departamento",
                "verbose_name_plural": "Configuración del Departamento",
            },
        ),
    ]
