# Generated by Django 4.2.30 on 2026-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equivalencias", "0004_configuraciondepartamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuraciondepartamento",
            name="firma_imagen",
            field=models.ImageField(
                upload_to="private/firmas/", verbose_name="Imagen de firma"
            ),
        ),
    ]
