# Generated by Django 4.2.30 on 2026-07-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistorialDecisiones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correo_message_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("correo_remitente", models.EmailField(max_length=254)),
                ("correo_asunto", models.CharField(max_length=500)),
                ("correo_cuerpo", models.TextField()),
                ("fecha_recepcion", models.DateTimeField()),
                ("categoria_ia", models.CharField(blank=True, max_length=100)),
                ("resumen_ia", models.TextField(blank=True)),
                (
                    "accion_propuesta_ia",
                    models.TextField(
                        blank=True,
                        help_text="Borrador de respuesta o acción sugerida por el LLM.",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de revisión"),
                            ("esperando_texto", "Esperando texto modificado"),
                            ("aprobado", "Aprobado"),
                            ("modificado", "Modificado"),
                            ("descartado", "Descartado"),
                            ("enviado", "Acción ejecutada"),
                            ("error", "Error al ejecutar"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "texto_final",
                    models.TextField(
                        blank=True,
                        help_text="Texto realmente enviado: igual a accion_propuesta_ia si fue 'aprobado', editado por el admin si fue 'modificado'.",
                    ),
                ),
                (
                    "decidido_por_telegram_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("fecha_decision", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("telegram_chat_id", models.BigIntegerField(blank=True, null=True)),
                ("telegram_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "telegram_prompt_message_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Decisión sobre correo",
                "verbose_name_plural": "Historial de Decisiones",
                "ordering": ["-fecha_recepcion", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MicrosoftToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cuenta_id",
                    models.CharField(
                        default="principal",
                        help_text="Identificador de la casilla. Una sola cuenta institucional por ahora.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("token_data", models.JSONField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Token de Microsoft",
                "verbose_name_plural": "Tokens de Microsoft",
            },
        ),
    ]
