# Generated by Django 5.2.6 on 2025-09-29 18:32

import carrera_academica.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planta_docente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembreteAnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anio",
                    models.IntegerField(
                        help_text="Año al que corresponde este membrete", unique=True
                    ),
                ),
                ("logo", models.ImageField(upload_to="membretes/logos/")),
                (
                    "frase",
                    models.CharField(
                        help_text="Frase del encabezado para este año", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Membrete Anual",
                "verbose_name_plural": "Membretes Anuales",
            },
        ),
        migrations.CreateModel(
            name="MiembroExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "universidad_origen",
                    models.CharField(
                        help_text="Ej: Universidad Nacional de Buenos Aires",
                        max_length=255,
                    ),
                ),
                (
                    "cargo_info",
                    models.CharField(
                        help_text="Ej: Titular con Dedicación Exclusiva", max_length=255
                    ),
                ),
                (
                    "resolucion_designacion",
                    models.CharField(
                        blank=True,
                        help_text="Nro. de resolución de designación a la junta",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro Externo",
                "verbose_name_plural": "Miembros Externos",
            },
        ),
        migrations.CreateModel(
            name="PlantillaDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_formulario",
                    models.CharField(
                        choices=[
                            ("F02", "F02"),
                            ("F04", "F04"),
                            ("F05", "F05"),
                            ("F06", "F06"),
                            ("F07", "F07"),
                            ("F13", "F13"),
                        ],
                        max_length=4,
                    ),
                ),
                ("archivo", models.FileField(upload_to="plantillas_documentos/")),
                ("descripcion", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Plantilla de Documento",
                "verbose_name_plural": "Plantillas de Documentos",
            },
        ),
        migrations.CreateModel(
            name="Veedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "claustro",
                    models.CharField(
                        choices=[("ALU", "Alumno"), ("GRA", "Graduado")], max_length=3
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarreraAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_expediente",
                    models.CharField(
                        blank=True,
                        help_text="Ej: 12345/2024",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_vencimiento_original", models.DateField()),
                (
                    "fecha_vencimiento_actual",
                    models.DateField(help_text="Se actualiza con las prórrogas"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACT", "Activa"),
                            ("STB", "En Standby (Licencia)"),
                            ("FIN", "Finalizada"),
                            ("VEN", "Vencida"),
                        ],
                        default="ACT",
                        max_length=3,
                    ),
                ),
                ("fecha_finalizacion", models.DateTimeField(blank=True, null=True)),
                (
                    "cargo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrera_academica",
                        to="planta_docente.cargo",
                    ),
                ),
                (
                    "resolucion_designacion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolución de designación del cargo (CSU o CD)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ca_designacion",
                        to="planta_docente.resolucion",
                    ),
                ),
                (
                    "resolucion_puesta_en_funcion",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolución de puesta en función (Decano)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ca_puesta_en_funcion",
                        to="planta_docente.resolucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_evaluacion", models.PositiveIntegerField()),
                ("fecha_iniciada", models.DateField(default=django.utils.timezone.now)),
                (
                    "anios_evaluados",
                    models.JSONField(
                        default=list,
                        help_text="Lista de años que cubre esta evaluación, ej: [2022, 2023]",
                    ),
                ),
                (
                    "fecha_evaluacion",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha y Hora de la Evaluación",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PRO", "Programada"),
                            ("REA", "Realizada"),
                            ("CAN", "Cancelada"),
                        ],
                        default="PRO",
                        max_length=3,
                    ),
                ),
                (
                    "carrera_academica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="carrera_academica.carreraacademica",
                    ),
                ),
            ],
            options={
                "ordering": ["numero_evaluacion"],
                "unique_together": {("carrera_academica", "numero_evaluacion")},
            },
        ),
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_formulario",
                    models.CharField(
                        choices=[
                            ("CV", "Curriculum Vitae"),
                            ("F01", "F01"),
                            ("F02", "F02"),
                            ("F03", "F03"),
                            ("F04", "F04"),
                            ("F05", "F05"),
                            ("F06", "F06"),
                            ("F07", "F07"),
                            ("F08", "F08"),
                            ("F09", "F09"),
                            ("F10", "F10"),
                            ("F11", "F11"),
                            ("F12", "F12"),
                            ("F13", "F13"),
                            ("ENC", "Encuesta"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PEN", "Pendiente"),
                            ("ENT", "Entregado"),
                            ("OBS", "Observado"),
                        ],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                ("fecha_entrega", models.DateField(blank=True, null=True)),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=carrera_academica.models.get_ca_upload_path,
                    ),
                ),
                (
                    "anio_correspondiente",
                    models.IntegerField(
                        blank=True, help_text="Ej: 2024 (para F04-F07, F13)", null=True
                    ),
                ),
                (
                    "carrera_academica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios",
                        to="carrera_academica.carreraacademica",
                    ),
                ),
                (
                    "evaluacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios",
                        to="carrera_academica.evaluacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JuntaEvaluadora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asistencia_status", models.JSONField(blank=True, default=dict)),
                (
                    "carrera_academica",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="junta_evaluadora",
                        to="carrera_academica.carreraacademica",
                    ),
                ),
                (
                    "miembro_interno_suplente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="juntas_suplente_interno",
                        to="planta_docente.docente",
                    ),
                ),
                (
                    "miembro_interno_titular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="juntas_titular_interno",
                        to="planta_docente.docente",
                    ),
                ),
                (
                    "miembros_externos_suplentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="juntas_suplente_externo",
                        to="carrera_academica.miembroexterno",
                    ),
                ),
                (
                    "miembros_externos_titulares",
                    models.ManyToManyField(
                        blank=True,
                        related_name="juntas_titular_externo",
                        to="carrera_academica.miembroexterno",
                    ),
                ),
                (
                    "veedor_alumno_suplente",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"claustro": "ALU"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veedor_alumno_sup",
                        to="carrera_academica.veedor",
                    ),
                ),
                (
                    "veedor_alumno_titular",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"claustro": "ALU"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veedor_alumno_tit",
                        to="carrera_academica.veedor",
                    ),
                ),
                (
                    "veedor_graduado_suplente",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"claustro": "GRA"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veedor_graduado_sup",
                        to="carrera_academica.veedor",
                    ),
                ),
                (
                    "veedor_graduado_titular",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"claustro": "GRA"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="veedor_graduado_tit",
                        to="carrera_academica.veedor",
                    ),
                ),
            ],
        ),
    ]
