# Generated by Django 5.2.6 on 2025-10-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrera_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carreraacademica',
            options={'verbose_name': 'Carrera Académica', 'verbose_name_plural': 'Carreras Académicas'},
        ),
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['numero_evaluacion'], 'verbose_name': 'Evaluación', 'verbose_name_plural': 'Evaluaciones'},
        ),
        migrations.AlterModelOptions(
            name='formulario',
            options={'verbose_name': 'Formulario', 'verbose_name_plural': 'Formularios'},
        ),
        migrations.AlterModelOptions(
            name='juntaevaluadora',
            options={'verbose_name': 'Junta Evaluadora', 'verbose_name_plural': 'Juntas Evaluadoras'},
        ),
    ]
