# Generated by Django 5.2.6 on 2025-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0002_alter_carreraacademica_options_and_more"),
        (
            "planta_docente",
            "0004_alter_correo_options_asignatura_asig_nivel_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carreraacademica",
            options={
                "ordering": ["fecha_vencimiento_actual"],
                "verbose_name": "Carrera Académica",
                "verbose_name_plural": "Carreras Académicas",
            },
        ),
        migrations.AddIndex(
            model_name="carreraacademica",
            index=models.Index(fields=["estado"], name="ca_estado_idx"),
        ),
        migrations.AddIndex(
            model_name="carreraacademica",
            index=models.Index(
                fields=["fecha_vencimiento_actual"], name="ca_venc_actual_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carreraacademica",
            index=models.Index(fields=["numero_expediente"], name="ca_expediente_idx"),
        ),
        migrations.AddIndex(
            model_name="carreraacademica",
            index=models.Index(
                fields=["estado", "fecha_vencimiento_actual"],
                name="ca_estado_fecha_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="carreraacademica",
            index=models.Index(fields=["cargo"], name="ca_cargo_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluacion",
            index=models.Index(fields=["carrera_academica"], name="eval_ca_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluacion",
            index=models.Index(fields=["estado"], name="eval_estado_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluacion",
            index=models.Index(fields=["fecha_evaluacion"], name="eval_fecha_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluacion",
            index=models.Index(
                fields=["carrera_academica", "numero_evaluacion"],
                name="eval_ca_num_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formulario",
            index=models.Index(fields=["carrera_academica"], name="form_ca_idx"),
        ),
        migrations.AddIndex(
            model_name="formulario",
            index=models.Index(fields=["tipo_formulario"], name="form_tipo_idx"),
        ),
        migrations.AddIndex(
            model_name="formulario",
            index=models.Index(fields=["estado"], name="form_estado_idx"),
        ),
        migrations.AddIndex(
            model_name="formulario",
            index=models.Index(fields=["anio_correspondiente"], name="form_anio_idx"),
        ),
        migrations.AddIndex(
            model_name="formulario",
            index=models.Index(
                fields=["carrera_academica", "estado"], name="form_ca_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formulario",
            index=models.Index(
                fields=["carrera_academica", "tipo_formulario", "anio_correspondiente"],
                name="form_ca_tipo_anio_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="juntaevaluadora",
            index=models.Index(fields=["carrera_academica"], name="junta_ca_idx"),
        ),
    ]
