# Generated by Django 5.2.7 on 2025-11-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0003_alter_carreraacademica_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carreraacademica",
            name="anios_pausados",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de años que no se evaluarán. Formato: [{'anio': 2022, 'motivo': '...', 'fecha': '2022-03-15', 'usuario': 'admin'}]",
                verbose_name="Años Pausados",
            ),
        ),
    ]
