# Generated by Django 5.2.7 on 2026-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0004_carreraacademica_anios_pausados"),
    ]

    operations = [
        migrations.AddField(
            model_name="carreraacademica",
            name="observaciones_cierre",
            field=models.TextField(blank=True, verbose_name="Observaciones del Cierre"),
        ),
        migrations.AddField(
            model_name="carreraacademica",
            name="resultado_cierre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("aprobada_redesigna", "Aprobada - Acepta Redesignación"),
                    ("aprobada_rechaza", "Aprobada - Rechaza Redesignación"),
                    ("renuncia", "Renuncia"),
                    ("no_aprobada", "No Aprobada"),
                    ("jubilacion", "Jubilación"),
                ],
                help_text="Resultado al finalizar la Carrera Académica",
                max_length=30,
                null=True,
                verbose_name="Resultado del Cierre",
            ),
        ),
    ]
