# Generated by Django 5.2.7 on 2026-03-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrera_academica', '0005_agregar_resultado_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreraacademica',
            name='ca_anterior',
            field=models.OneToOneField(blank=True, help_text='Expediente de CA del cual este es continuación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ca_siguiente', to='carrera_academica.carreraacademica', verbose_name='CA Anterior'),
        ),
    ]
