# Generated by Django 5.2.7 on 2026-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0006_agregar_vinculacion_ca_anterior"),
    ]

    operations = [
        migrations.AddField(
            model_name="carreraacademica",
            name="fecha_archivo",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Archivo"
            ),
        ),
        migrations.AddField(
            model_name="carreraacademica",
            name="motivo_archivo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jubilacion_cercana", "Jubilación Cercana - Cargo a Interino"),
                    ("renuncia_condicional", "Renuncia Condicional - Mantiene Cargo"),
                    ("administrativo", "Motivo Administrativo"),
                    ("otro", "Otro"),
                ],
                help_text="Motivo por el cual se archivó la CA sin workflow formal de cierre",
                max_length=30,
                null=True,
                verbose_name="Motivo de Archivo",
            ),
        ),
        migrations.AddField(
            model_name="carreraacademica",
            name="observaciones_archivo",
            field=models.TextField(
                blank=True, verbose_name="Observaciones del Archivo"
            ),
        ),
        migrations.AlterField(
            model_name="carreraacademica",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ACT", "Activa"),
                    ("STB", "En Standby (Licencia)"),
                    ("ARCH", "Archivada"),
                    ("FIN", "Finalizada"),
                    ("VEN", "Vencida"),
                ],
                default="ACT",
                max_length=4,
            ),
        ),
    ]
