# Generated by Django 5.2.7 on 2026-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0007_aumentar_max_length_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carreraacademica",
            name="motivo_archivo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jubilacion_cercana", "Jubilación Cercana"),
                    ("renuncia_condicional", "Renuncia Condicional"),
                    ("administrativo", "Motivo Administrativo"),
                    ("otro", "Otro"),
                ],
                help_text="Motivo por el cual se archivó la CA sin workflow formal de cierre",
                max_length=30,
                null=True,
                verbose_name="Motivo de Archivo",
            ),
        ),
    ]
