# Generated by Django 4.2.30 on 2026-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0008_alter_carreraacademica_motivo_archivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membreteanual",
            name="logo",
            field=models.ImageField(upload_to="private/membretes/logos/"),
        ),
        migrations.AlterField(
            model_name="plantilladocumento",
            name="archivo",
            field=models.FileField(upload_to="private/plantillas_documentos/"),
        ),
    ]
