# Generated by Django 4.2.30 on 2026-04-28 20:32

import carrera_academica.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0009_alter_membreteanual_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="archivo",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=carrera_academica.models.get_ca_upload_path,
            ),
        ),
    ]
