# Generated by Django 4.2.30 on 2026-05-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0026_alter_planificacionanual_archivo_and_more"),
        ("carrera_academica", "0010_alter_formulario_archivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="VeedorEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("legajo", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Veedor Estudiante",
                "verbose_name_plural": "Veedores Estudiantes",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="VeedorGraduado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                (
                    "titulo",
                    models.CharField(help_text="Ej: Ingeniero Civil", max_length=200),
                ),
                ("año_egreso", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Veedor Graduado",
                "verbose_name_plural": "Veedores Graduados",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Jurado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        editable=False,
                        help_text="Generado automáticamente: Apellido1 - Apellido2 - Apellido3",
                        max_length=300,
                        unique=True,
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        choices=[
                            ("civil", "Dpto. de Civil"),
                            ("electrica", "Dpto. de Electrica"),
                            ("industrial", "Dpto. de Industrial"),
                            ("mecanica", "Dpto. de Mecanica"),
                            ("quimica", "Dpto. de Quimica"),
                            ("sistema", "Dpto. de Sistema de Informacion"),
                            ("basicas", "Dpto de Ciencias Basicas"),
                        ],
                        default="civil",
                        help_text="Departamento al que pertenece este jurado",
                        max_length=15,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones o notas internas sobre este jurado",
                    ),
                ),
                (
                    "profesor_suplente_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_suplente_1",
                        to="planta_docente.docente",
                        verbose_name="Profesor Suplente 1",
                    ),
                ),
                (
                    "profesor_suplente_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_suplente_2",
                        to="planta_docente.docente",
                        verbose_name="Profesor Suplente 2",
                    ),
                ),
                (
                    "profesor_suplente_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_suplente_3",
                        to="planta_docente.docente",
                        verbose_name="Profesor Suplente 3",
                    ),
                ),
                (
                    "profesor_titular_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_titular_1",
                        to="planta_docente.docente",
                        verbose_name="Profesor Titular 1",
                    ),
                ),
                (
                    "profesor_titular_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_titular_2",
                        to="planta_docente.docente",
                        verbose_name="Profesor Titular 2",
                    ),
                ),
                (
                    "profesor_titular_3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_titular_3",
                        to="planta_docente.docente",
                        verbose_name="Profesor Titular 3",
                    ),
                ),
                (
                    "veedor_estudiante_suplente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_estudiante_suplente",
                        to="carrera_academica.veedorestudiante",
                        verbose_name="Veedor Estudiante Suplente",
                    ),
                ),
                (
                    "veedor_estudiante_titular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_estudiante_titular",
                        to="carrera_academica.veedorestudiante",
                        verbose_name="Veedor Estudiante Titular",
                    ),
                ),
                (
                    "veedor_graduado_suplente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_graduado_suplente",
                        to="carrera_academica.veedorgraduado",
                        verbose_name="Veedor Graduado Suplente",
                    ),
                ),
                (
                    "veedor_graduado_titular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurado_graduado_titular",
                        to="carrera_academica.veedorgraduado",
                        verbose_name="Veedor Graduado Titular",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jurado",
                "verbose_name_plural": "Jurados",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.AddField(
            model_name="carreraacademica",
            name="jurado",
            field=models.ForeignKey(
                blank=True,
                help_text="Jurado asignado para la evaluación de esta CA",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carreras_academicas",
                to="carrera_academica.jurado",
                verbose_name="Jurado Evaluador",
            ),
        ),
    ]
