# Generated by Django 4.2.30 on 2026-05-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0011_veedorestudiante_veedorgraduado_jurado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Universidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        help_text="Ej: UTN, UBA, UNLP, UNC, etc.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                ("es_utn", models.BooleanField(default=False)),
                (
                    "regional",
                    models.CharField(
                        blank=True,
                        help_text="Ej: FRLP, FRC, FRA, etc. Solo para UTN",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Universidad",
                "verbose_name_plural": "Universidades",
                "ordering": ["sigla"],
            },
        ),
        migrations.CreateModel(
            name="JuradoExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("titular", "Profesor Titular"),
                            ("asociado", "Profesor Asociado"),
                            ("adjunto", "Profesor Adjunto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "es_investigador",
                    models.BooleanField(
                        default=False, help_text="¿Es Docente Investigador?"
                    ),
                ),
                ("es_jubilado", models.BooleanField(default=False)),
                (
                    "archivo_resolucion",
                    models.FileField(
                        blank=True,
                        help_text="PDF de la resolución que avala el cargo",
                        null=True,
                        upload_to="jurados_externos/resoluciones/",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_alta", models.DateTimeField(auto_now_add=True)),
                (
                    "universidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jurados_externos",
                        to="carrera_academica.universidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jurado Externo",
                "verbose_name_plural": "Jurados Externos",
                "ordering": ["apellido", "nombre"],
            },
        ),
    ]
