# Generated by Django 4.2.30 on 2026-05-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0026_alter_planificacionanual_archivo_and_more"),
        ("carrera_academica", "0012_agregar_jurados_externos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurado",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="departamento",
            field=models.CharField(
                choices=[
                    ("civil", "Dpto. de Civil"),
                    ("electrica", "Dpto. de Electrica"),
                    ("industrial", "Dpto. de Industrial"),
                    ("mecanica", "Dpto. de Mecanica"),
                    ("quimica", "Dpto. de Quimica"),
                    ("sistema", "Dpto. de Sistema de Informacion"),
                    ("basicas", "Dpto de Ciencias Basicas"),
                ],
                help_text="Departamento al que pertenece este jurado",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="nombre",
            field=models.CharField(
                editable=False,
                help_text="Se genera automáticamente con los apellidos de los 3 titulares",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="notas",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="profesor_suplente_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jurados_como_suplente_1",
                to="planta_docente.docente",
                verbose_name="Suplente 1",
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="profesor_suplente_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jurados_como_suplente_2",
                to="carrera_academica.juradoexterno",
                verbose_name="Suplente 2",
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="profesor_suplente_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jurados_como_suplente_3",
                to="carrera_academica.juradoexterno",
                verbose_name="Suplente 3",
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="profesor_titular_1",
            field=models.ForeignKey(
                help_text="Debe ser docente de la planta de UTN-FRLP",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jurados_como_titular_1",
                to="planta_docente.docente",
                verbose_name="Profesor Titular 1 (Interno)",
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="profesor_titular_2",
            field=models.ForeignKey(
                help_text="Puede ser de otra regional UTN u otra universidad",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jurados_como_titular_2",
                to="carrera_academica.juradoexterno",
                verbose_name="Profesor Titular 2 (Externo)",
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="profesor_titular_3",
            field=models.ForeignKey(
                help_text="Debe ser de otra Universidad Nacional (UBA, UNLP, etc.)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jurados_como_titular_3",
                to="carrera_academica.juradoexterno",
                verbose_name="Profesor Titular 3 (Universidad Externa)",
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="veedor_estudiante_suplente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jurados_como_estudiante_suplente",
                to="carrera_academica.veedorestudiante",
                verbose_name="Veedor Estudiante Suplente",
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="veedor_estudiante_titular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jurados_como_estudiante_titular",
                to="carrera_academica.veedorestudiante",
                verbose_name="Veedor Estudiante Titular",
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="veedor_graduado_suplente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jurados_como_graduado_suplente",
                to="carrera_academica.veedorgraduado",
                verbose_name="Veedor Graduado Suplente",
            ),
        ),
        migrations.AlterField(
            model_name="jurado",
            name="veedor_graduado_titular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jurados_como_graduado_titular",
                to="carrera_academica.veedorgraduado",
                verbose_name="Veedor Graduado Titular",
            ),
        ),
    ]
