# Generated by Django 4.2.30 on 2026-06-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0013_modificar_jurado_con_externos"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=4, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo de Formulario",
                "verbose_name_plural": "Tipos de Formulario",
                "ordering": ["codigo"],
            },
        ),
    ]
