# Generated by Django 4.2.30 on 2026-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0015_tipoformulario_datos_iniciales"),
    ]

    operations = [
        migrations.AddField(
            model_name="carreraacademica",
            name="cantidad_notificaciones",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número de notificaciones enviadas al docente",
                verbose_name="Cantidad de Notificaciones",
            ),
        ),
        migrations.AddField(
            model_name="carreraacademica",
            name="fecha_ultima_notificacion",
            field=models.DateTimeField(
                blank=True,
                help_text="Última vez que se envió una notificación al docente sobre documentación pendiente",
                null=True,
                verbose_name="Fecha de Última Notificación",
            ),
        ),
    ]
