# Generated by Django 5.2.7 on 2026-06-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0016_add_notificacion_tracking_to_carreraacademica"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluacion",
            name="calificacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INS", "Insuficiente"),
                    ("REG", "Regular"),
                    ("BUE", "Bueno"),
                    ("MBU", "Muy Bueno"),
                    ("EXC", "Excelente"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
