# Generated by Django 5.2.7 on 2026-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0017_add_calificacion_to_evaluacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="comprimido",
            field=models.BooleanField(default=False),
        ),
    ]
