# Generated by Django 4.2.30 on 2026-08-10 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carrera_academica", "0018_add_comprimido_to_formulario"),
    ]

    operations = [
        migrations.AddField(
            model_name="juradoexterno",
            name="dni",
            field=models.IntegerField(
                blank=True,
                help_text="Usado para verificar identidad en el Portal de Jurados",
                null=True,
                unique=True,
                verbose_name="DNI",
            ),
        ),
        migrations.AddField(
            model_name="veedorestudiante",
            name="dni",
            field=models.IntegerField(
                blank=True,
                help_text="Usado para verificar identidad en el Portal de Jurados",
                null=True,
                unique=True,
                verbose_name="DNI",
            ),
        ),
        migrations.AddField(
            model_name="veedorgraduado",
            name="dni",
            field=models.IntegerField(
                blank=True,
                help_text="Usado para verificar identidad en el Portal de Jurados",
                null=True,
                unique=True,
                verbose_name="DNI",
            ),
        ),
        migrations.CreateModel(
            name="TokenPortalJurado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_persona",
                    models.CharField(
                        choices=[
                            ("docente", "Docente (interno)"),
                            ("jurado_externo", "Jurado Externo"),
                            ("veedor_graduado", "Veedor Graduado"),
                            ("veedor_estudiante", "Veedor Estudiante"),
                        ],
                        max_length=20,
                    ),
                ),
                ("persona_id", models.PositiveIntegerField()),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("expira", models.DateTimeField()),
                ("revocado", models.BooleanField(default=False)),
                ("fecha_revocado", models.DateTimeField(blank=True, null=True)),
                ("ultimo_uso", models.DateTimeField(blank=True, null=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Portal de Jurado",
                "verbose_name_plural": "Tokens Portal de Jurados",
            },
        ),
        migrations.CreateModel(
            name="AccesoPortalJurado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_persona",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("docente", "Docente (interno)"),
                            ("jurado_externo", "Jurado Externo"),
                            ("veedor_graduado", "Veedor Graduado"),
                            ("veedor_estudiante", "Veedor Estudiante"),
                        ],
                        max_length=20,
                    ),
                ),
                ("persona_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("link_ok", "Link verificado correctamente"),
                            ("link_fail_token", "Token inválido/expirado/revocado"),
                            ("link_fail_dni", "DNI incorrecto"),
                            ("vista_dashboard", "Vio listado de CAs"),
                            ("vista_documento", "Vio/descargó un documento"),
                            ("descarga_expediente", "Descargó expediente completo"),
                        ],
                        max_length=25,
                    ),
                ),
                ("exitoso", models.BooleanField(default=True)),
                ("detalle", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "carrera_academica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accesos_portal_jurado",
                        to="carrera_academica.carreraacademica",
                    ),
                ),
                (
                    "formulario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="carrera_academica.formulario",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accesos",
                        to="carrera_academica.tokenportaljurado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acceso Portal de Jurado",
                "verbose_name_plural": "Accesos Portal de Jurados",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="tokenportaljurado",
            index=models.Index(
                fields=["tipo_persona", "persona_id"],
                name="carrera_aca_tipo_pe_009c27_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accesoportaljurado",
            index=models.Index(
                fields=["tipo_persona", "persona_id", "-fecha"],
                name="carrera_aca_tipo_pe_1f14b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accesoportaljurado",
            index=models.Index(
                fields=["carrera_academica", "-fecha"],
                name="carrera_aca_carrera_4a9481_idx",
            ),
        ),
    ]
