# Generated by Django 4.2.30 on 2026-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0019_portal_jurados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesoportaljurado",
            name="accion",
            field=models.CharField(
                choices=[
                    ("link_ok", "Link verificado correctamente"),
                    ("link_fail_token", "Token inválido/expirado/revocado"),
                    ("link_fail_dni", "DNI incorrecto"),
                    ("vista_dashboard", "Vio listado de CAs"),
                    ("vista_detalle_ca", "Vio el detalle de un expediente"),
                    ("vista_documento", "Vio/descargó un documento"),
                    ("descarga_expediente", "Descargó expediente completo"),
                ],
                max_length=25,
            ),
        ),
    ]
