# Generated by Django 4.2.30 on 2026-08-31 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0021_migrar_junta_evaluadora_a_jurado"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JuntaEvaluadora",
        ),
        migrations.DeleteModel(
            name="MiembroExterno",
        ),
        migrations.DeleteModel(
            name="Veedor",
        ),
    ]
