# Generated by Django 4.2.30 on 2026-08-31 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carrera_academica", "0022_eliminar_junta_evaluadora"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenPortalConcursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("password_hash", models.CharField(max_length=64)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("expira", models.DateTimeField()),
                ("revocado", models.BooleanField(default=False)),
                ("ultimo_uso", models.DateTimeField(blank=True, null=True)),
                (
                    "carrera_academica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens_concursos",
                        to="carrera_academica.carreraacademica",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token Portal de Concursos",
                "verbose_name_plural": "Tokens Portal de Concursos",
                "indexes": [
                    models.Index(
                        fields=["carrera_academica"],
                        name="carrera_aca_carrera_7f79c2_idx",
                    )
                ],
            },
        ),
    ]
