# Generated by Django 4.2.30 on 2026-08-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0023_token_portal_concursos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenportalconcursos",
            name="password_hash",
            field=models.CharField(max_length=128),
        ),
    ]
