# Generated by Django 4.2.30 on 2026-09-01 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carrera_academica", "0024_alter_tokenportalconcursos_password_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesoportaljurado",
            name="token_concursos",
            field=models.ForeignKey(
                blank=True,
                help_text="Set en vez de 'token' cuando el acceso es del Portal de Concursos (una casilla, no una persona).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accesos",
                to="carrera_academica.tokenportalconcursos",
            ),
        ),
        migrations.AlterField(
            model_name="accesoportaljurado",
            name="accion",
            field=models.CharField(
                choices=[
                    ("link_ok", "Link verificado correctamente"),
                    ("link_fail_token", "Token inválido/expirado/revocado"),
                    ("link_fail_dni", "DNI incorrecto"),
                    ("link_fail_password", "Contraseña incorrecta"),
                    ("vista_dashboard", "Vio listado de CAs"),
                    ("vista_detalle_ca", "Vio el detalle de un expediente"),
                    ("vista_documento", "Vio/descargó un documento"),
                    ("descarga_expediente", "Descargó expediente completo"),
                ],
                max_length=25,
            ),
        ),
    ]
