# Generated by Django 5.2.6 on 2025-09-29 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Bloque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("documento", models.IntegerField(unique=True)),
                ("legajo", models.IntegerField(unique=True)),
                ("fecha_nacimiento", models.DateField(default="1900-01-01")),
            ],
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("i", "I"),
                            ("ii", "II"),
                            ("iii", "III"),
                            ("iv", "IV"),
                            ("v", "V"),
                            ("vi", "VI"),
                            ("-", "-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("puntaje", models.IntegerField(default=0)),
                (
                    "departamento",
                    models.CharField(
                        choices=[
                            ("civil", "Dpto. de Civil"),
                            ("electrica", "Dpto. de Electrica"),
                            ("industrial", "Dpto. de Industrial"),
                            ("mecanica", "Dpto. de Mecanica"),
                            ("quimica", "Dpto. de Quimica"),
                            ("sistema", "Dpto. de Sistema de Informacion"),
                            ("basicas", "Dpto de Ciencias Basicas"),
                        ],
                        max_length=11,
                    ),
                ),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("civil", "Ing. Civil"),
                            ("electrica", "Ing. Electrica"),
                            ("industrial", "Ing. Industrial"),
                            ("mecanica", "Ing. Mecanica"),
                            ("quimica", "Ing. Quimica"),
                            ("sistema", "Ing. en Sistema de Informacion"),
                        ],
                        max_length=11,
                    ),
                ),
                ("obligatoria", models.BooleanField(default=True)),
                ("hora_semanal", models.PositiveIntegerField()),
                ("hora_total", models.PositiveIntegerField()),
                (
                    "dictado",
                    models.CharField(
                        choices=[
                            ("a", "Anual"),
                            ("c1", "1er. Cuatrimestre"),
                            ("c2", "2do. Cuatrimestre"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "area",
                    models.ManyToManyField(
                        blank=True,
                        related_name="area_asignatura",
                        to="planta_docente.area",
                    ),
                ),
                (
                    "bloque",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bloque_asignatura",
                        to="planta_docente.bloque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
                "ordering": ["-obligatoria", "nivel"],
            },
        ),
        migrations.CreateModel(
            name="Correo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("principal", models.BooleanField(default=True)),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correos",
                        to="planta_docente.docente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "caracter",
                    models.CharField(
                        choices=[
                            ("ord", "Ordinario"),
                            ("reg", "Regular"),
                            ("int", "Interino"),
                            ("adh", "Ad-Honorem"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("tit", "Titular"),
                            ("aso", "Asociado"),
                            ("adj", "Adjunto"),
                            ("jtp", "Jefe de Trabajos Practicos"),
                            ("atp1", "Ayudante de 1ra"),
                            ("atp2", "Ayudante de 2da"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "dedicacion",
                    models.CharField(
                        choices=[
                            ("ds", "Simple"),
                            ("se", "Semi-Exclusiva"),
                            ("de", "Exclusiva"),
                        ],
                        max_length=2,
                    ),
                ),
                ("cantidad_horas", models.FloatField(default=1)),
                ("fecha_inicio", models.DateField()),
                ("fecha_final", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("licencia", "Licencia"),
                            ("baja", "Baja"),
                        ],
                        default="activo",
                        max_length=10,
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_asignatura",
                        to="planta_docente.asignatura",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargo_docente",
                        to="planta_docente.docente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
                ("año", models.IntegerField()),
                (
                    "objeto",
                    models.CharField(
                        choices=[
                            ("alta", "Alta en el Cargo"),
                            ("baja", "Baja en el Cargo"),
                            ("redesignacion", "Redesignacion"),
                            ("puesta_funcion", "Puesta en Funcion"),
                            ("licencia_alta", "Alta de Licencia"),
                            ("licencia_baja", "Baja de Licencia"),
                            ("prorroga_ca", "Prorroga de Carrera Academica"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("dec", "Decano"),
                            ("cd", "Consejo Directivo"),
                            ("rec", "Rector"),
                            ("csu", "Consejo Superior"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resoluciones/"),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resoluciones",
                        to="planta_docente.cargo",
                    ),
                ),
            ],
        ),
    ]
