# Generated by Django 5.2.6 on 2025-10-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolucion",
            name="fecha_fin_licencia",
            field=models.DateField(
                blank=True,
                help_text="Solo para resoluciones de tipo 'Alta de Licencia' o 'Baja de Licencia'.",
                null=True,
                verbose_name="Fecha de Fin de Licencia",
            ),
        ),
        migrations.AddField(
            model_name="resolucion",
            name="fecha_inicio_licencia",
            field=models.DateField(
                blank=True,
                help_text="Solo para resoluciones de tipo 'Alta de Licencia'.",
                null=True,
                verbose_name="Fecha de Inicio de Licencia",
            ),
        ),
        migrations.AddField(
            model_name="resolucion",
            name="genera_prorroga_ca",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si esta licencia debe extender la fecha de vencimiento de la Carrera Académica.",
                verbose_name="Genera Prórroga en C.A.",
            ),
        ),
        migrations.AlterField(
            model_name="resolucion",
            name="objeto",
            field=models.CharField(
                choices=[
                    ("alta", "Alta en el Cargo"),
                    ("baja", "Baja en el Cargo"),
                    ("designacion", "Designacion"),
                    ("puesta_funcion", "Puesta en Funcion"),
                    ("licencia_alta", "Alta de Licencia"),
                    ("licencia_baja", "Baja de Licencia"),
                    ("prorroga_ca", "Prorroga de Carrera Academica"),
                ],
                max_length=15,
            ),
        ),
    ]
