# Generated by Django 5.2.6 on 2025-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0003_alter_cargo_options_alter_docente_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correo",
            options={"verbose_name": "Correo", "verbose_name_plural": "Correos"},
        ),
        migrations.AddIndex(
            model_name="asignatura",
            index=models.Index(fields=["nivel"], name="asig_nivel_idx"),
        ),
        migrations.AddIndex(
            model_name="asignatura",
            index=models.Index(fields=["departamento"], name="asig_depto_idx"),
        ),
        migrations.AddIndex(
            model_name="asignatura",
            index=models.Index(fields=["especialidad"], name="asig_especialidad_idx"),
        ),
        migrations.AddIndex(
            model_name="asignatura",
            index=models.Index(
                fields=["-obligatoria", "nivel"], name="asig_oblig_nivel_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["docente"], name="cargo_docente_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["asignatura"], name="cargo_asignatura_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["estado"], name="cargo_estado_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["caracter"], name="cargo_caracter_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["estado", "caracter"], name="cargo_estado_caracter_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["docente", "asignatura"], name="cargo_doc_asig_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["fecha_inicio"], name="cargo_fecha_inicio_idx"),
        ),
        migrations.AddIndex(
            model_name="correo",
            index=models.Index(fields=["docente"], name="correo_docente_idx"),
        ),
        migrations.AddIndex(
            model_name="correo",
            index=models.Index(
                fields=["docente", "principal"], name="correo_doc_principal_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="docente",
            index=models.Index(fields=["legajo"], name="doc_legajo_idx"),
        ),
        migrations.AddIndex(
            model_name="docente",
            index=models.Index(fields=["documento"], name="doc_documento_idx"),
        ),
        migrations.AddIndex(
            model_name="docente",
            index=models.Index(fields=["apellido"], name="doc_apellido_idx"),
        ),
        migrations.AddIndex(
            model_name="docente",
            index=models.Index(
                fields=["apellido", "nombre"], name="doc_apellido_nombre_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resolucion",
            index=models.Index(fields=["cargo"], name="res_cargo_idx"),
        ),
        migrations.AddIndex(
            model_name="resolucion",
            index=models.Index(fields=["objeto"], name="res_objeto_idx"),
        ),
        migrations.AddIndex(
            model_name="resolucion",
            index=models.Index(fields=["año"], name="res_anio_idx"),
        ),
        migrations.AddIndex(
            model_name="resolucion",
            index=models.Index(fields=["-año", "-numero"], name="res_anio_num_idx"),
        ),
        migrations.AddIndex(
            model_name="resolucion",
            index=models.Index(fields=["cargo", "objeto"], name="res_cargo_objeto_idx"),
        ),
    ]
