# Generated by Django 5.2.7 on 2025-11-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planta_docente",
            "0004_alter_correo_options_asignatura_asig_nivel_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="docente",
            name="fecha_jubilacion",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que el docente se jubiló",
                null=True,
                verbose_name="Fecha de Jubilación",
            ),
        ),
        migrations.AddField(
            model_name="docente",
            name="jubilado",
            field=models.BooleanField(
                default=False,
                help_text="Marcar si el docente está jubilado. Se excluirá de reportes de planta activa.",
                verbose_name="Jubilado",
            ),
        ),
        migrations.AddIndex(
            model_name="docente",
            index=models.Index(fields=["jubilado"], name="doc_jubilado_idx"),
        ),
    ]
