# Generated by Django 5.2.7 on 2025-11-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0005_docente_fecha_jubilacion_docente_jubilado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="fecha_renovacion",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que se solicitó la renovación",
                null=True,
                verbose_name="Fecha de Solicitud de Renovación",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="fecha_vencimiento_anterior",
            field=models.DateField(
                blank=True,
                help_text="Fecha de vencimiento antes de la renovación (para poder revertir)",
                null=True,
                verbose_name="Fecha de Vencimiento Anterior",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="renovacion_solicitada",
            field=models.BooleanField(
                default=False,
                help_text="Marca si se solicitó la renovación para este cargo",
                verbose_name="Renovación Solicitada",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="usuario_renovacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_renovados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que Renovó",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="fecha_vencimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Vencimiento"
            ),
        ),
    ]
