# Generated by Django 5.2.7 on 2025-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0006_cargo_fecha_renovacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="dias_acumulados_licencia_mj",
            field=models.IntegerField(
                default=0,
                help_text="Total de días en licencia por mayor jerarquía",
                verbose_name="Días Acumulados en Licencia M.J.",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="en_licencia_mayor_jerarquia",
            field=models.BooleanField(
                default=False,
                help_text="Indica si está en licencia por mayor jerarquía (suspende y extiende vencimiento)",
                verbose_name="En Licencia por Mayor Jerarquía",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="en_licencia_normal",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el cargo está en licencia normal (no suspende vencimiento)",
                verbose_name="En Licencia Normal",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="fecha_fin_licencia_normal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Fin Licencia Normal"
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="fecha_inicio_licencia_mj",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Inicio Licencia M.J."
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="fecha_inicio_licencia_normal",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Inicio Licencia Normal"
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="fecha_vencimiento_original_pre_licencia",
            field=models.DateField(
                blank=True,
                help_text="Guarda el vencimiento antes de la licencia M.J. para calcular prórroga",
                null=True,
                verbose_name="Fecha Vencimiento Original (pre-licencia)",
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("tit", "Titular"),
                    ("aso", "Asociado"),
                    ("adj", "Adjunto"),
                    ("jtp", "Jefe de Trabajos Practicos"),
                    ("atp1", "Ayudante de 1ra"),
                    ("atp2", "Ayudante de 2da"),
                    ("ads", "Adscripto"),
                ],
                max_length=4,
            ),
        ),
    ]
