# Generated by Django 5.2.7 on 2025-11-13 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0007_cargo_dias_acumulados_licencia_mj_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="cargo_anterior",
            field=models.OneToOneField(
                blank=True,
                help_text="Cargo del cual este es continuación",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargo_siguiente",
                to="planta_docente.cargo",
                verbose_name="Cargo Anterior",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="estado_continuidad",
            field=models.CharField(
                choices=[
                    ("activo", "Activo (en curso)"),
                    ("finalizado_sin_continuidad", "Finalizado sin continuidad"),
                    ("finalizado_con_continuidad", "Finalizado con continuidad"),
                ],
                default="activo",
                help_text="Indica si el cargo está activo o cómo finalizó",
                max_length=30,
                verbose_name="Estado de Continuidad",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="fecha_registro_continuidad",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Registro de Continuidad"
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="observaciones_finalizacion",
            field=models.TextField(
                blank=True,
                help_text="Información adicional sobre la finalización",
                null=True,
                verbose_name="Observaciones de Finalización",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="razon_finalizacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("renuncia", "Renuncia"),
                    ("jubilacion", "Jubilación"),
                    ("no_renovacion", "No Renovación"),
                    ("vencimiento", "Vencimiento"),
                    ("cambio_cargo", "Cambio de Cargo"),
                    ("promocion", "Promoción"),
                    ("redistribucion", "Redistribución"),
                    ("otro", "Otro"),
                ],
                max_length=20,
                null=True,
                verbose_name="Razón de Finalización",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="tipo_continuidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mismo_cargo", "Renovación en mismo cargo"),
                    ("promocion", "Promoción (misma asignatura)"),
                    ("cambio_asignatura", "Cambio de asignatura"),
                    ("cambio_dedicacion", "Cambio de dedicación"),
                    ("otro", "Otro"),
                ],
                help_text="Tipo de relación con el cargo anterior",
                max_length=20,
                null=True,
                verbose_name="Tipo de Continuidad",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="usuario_registro_continuidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_continuidad_registrada",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que Registró Continuidad",
            ),
        ),
    ]
