# Generated by Django 5.2.7 on 2025-11-14 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0008_agregar_campos_continuidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="cargo_base",
            field=models.ForeignKey(
                blank=True,
                help_text="Cargo del cual salió en licencia por mayor jerarquía para tomar este cargo temporal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargo_temporal_mj",
                to="planta_docente.cargo",
                verbose_name="Cargo Base",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="es_cargo_mayor_jerarquia",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este cargo es temporal por mayor jerarquía",
                verbose_name="Es Cargo de Mayor Jerarquía",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="fecha_fin_cargo_mj",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Fin Cargo M.J."
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="fecha_inicio_cargo_mj",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Inicio Cargo M.J."
            ),
        ),
    ]
