# Generated by Django 5.2.7 on 2025-11-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planta_docente",
            "0009_cargo_cargo_base_cargo_es_cargo_mayor_jerarquia_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="dedicacion",
            field=models.CharField(
                choices=[
                    ("ms", "0.5 Simple"),
                    ("ds", "Simple"),
                    ("se", "Semi-Exclusiva"),
                    ("de", "Exclusiva"),
                ],
                max_length=2,
            ),
        ),
    ]
