# Generated by Django 5.2.7 on 2025-11-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0010_alter_cargo_dedicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="descripcion_cargo_mj",
            field=models.CharField(
                blank=True,
                help_text="Descripción del cargo de mayor jerarquía (si no es cargo docente)",
                max_length=200,
                null=True,
                verbose_name="Descripción Cargo M.J.",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="institucion_cargo_mj",
            field=models.CharField(
                blank=True,
                help_text="Institución donde ejerce el cargo de mayor jerarquía",
                max_length=200,
                null=True,
                verbose_name="Institución",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="tipo_cargo_mj",
            field=models.CharField(
                blank=True,
                choices=[
                    ("docente", "Cargo Docente"),
                    ("gestion_facultad", "Gestión en Facultad"),
                    ("gestion_universidad", "Gestión en Universidad"),
                    ("gestion_dpto", "Gestión en Departamento"),
                    ("externo", "Cargo Externo"),
                    ("otro", "Otro"),
                ],
                help_text="Tipo de cargo de mayor jerarquía",
                max_length=30,
                null=True,
                verbose_name="Tipo de Cargo M.J.",
            ),
        ),
    ]
