# Generated by Django 5.2.7 on 2025-11-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0011_cargo_descripcion_cargo_mj_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="numero_comisiones",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cantidad de comisiones en las que se divide la asignatura",
                null=True,
                verbose_name="Número de Comisiones",
            ),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="numero_estudiantes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Promedio histórico de estudiantes en la asignatura",
                null=True,
                verbose_name="Número de Estudiantes",
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="cantidad_comisiones",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número de comisiones que atiende este cargo",
                verbose_name="Cantidad de Comisiones",
            ),
        ),
    ]
