# Generated by Django 5.2.7 on 2025-11-19 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0012_asignatura_numero_comisiones_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadSustantiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("docencia_grado", "Docencia - Grado"),
                            ("docencia_posgrado", "Docencia - Posgrado"),
                            ("investigacion", "Investigación"),
                            ("extension", "Extensión"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "tipo_actividad",
                    models.CharField(
                        choices=[
                            ("doc_grado_segundo", "Docencia - Segundo curso de grado"),
                            ("doc_grado_electiva", "Docencia - Asignatura electiva"),
                            (
                                "doc_grado_pf_dir",
                                "Docencia - Dirección de proyecto final",
                            ),
                            (
                                "doc_grado_pf_codir",
                                "Docencia - Codirección de proyecto final",
                            ),
                            ("doc_grado_tutoria", "Docencia - Tutorías de estudiantes"),
                            (
                                "doc_grado_ps_dir",
                                "Docencia - Dirección de prácticas supervisadas",
                            ),
                            (
                                "doc_grado_ps_sup",
                                "Docencia - Supervisión de prácticas supervisadas",
                            ),
                            (
                                "doc_grado_tc_dir",
                                "Docencia - Dirección de trabajos de campo",
                            ),
                            (
                                "doc_grado_tc_sup",
                                "Docencia - Supervisión de trabajos de campo",
                            ),
                            (
                                "doc_pos_curso",
                                "Docencia - Curso o seminario de posgrado",
                            ),
                            (
                                "doc_pos_tesis_dir",
                                "Docencia - Dirección de tesis de posgrado",
                            ),
                            (
                                "doc_pos_tesis_codir",
                                "Docencia - Codirección de tesis de posgrado",
                            ),
                            (
                                "doc_pos_pi_dir",
                                "Docencia - Dirección de proyecto integrador",
                            ),
                            (
                                "doc_pos_pi_codir",
                                "Docencia - Codirección de proyecto integrador",
                            ),
                            ("inv_pid", "Investigación - Participación en PID UTN"),
                            ("ext_curso", "Extensión - Curso o seminario"),
                            ("ext_capacitacion", "Extensión - Capacitación"),
                            (
                                "ext_voluntariado",
                                "Extensión - Voluntariado universitario",
                            ),
                            ("ext_servicio", "Extensión - Servicio al medio"),
                            ("ext_transferencia", "Extensión - Transferencia al medio"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Actividad",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Detalle específico de la función sustantiva",
                        verbose_name="Descripción Detallada",
                    ),
                ),
                (
                    "horas_semanales",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cantidad aproximada de horas dedicadas",
                        null=True,
                        verbose_name="Horas Semanales Estimadas",
                    ),
                ),
                (
                    "codigo_proyecto",
                    models.CharField(
                        blank=True,
                        help_text="Ej: PID UTN, código de asignatura electiva, etc.",
                        max_length=50,
                        verbose_name="Código de Proyecto/Curso",
                    ),
                ),
                (
                    "nombre_proyecto",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Nombre del Proyecto/Curso",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Inicio de la función sustantiva",
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Fin de la función (dejar vacío si es indefinida)",
                        null=True,
                        verbose_name="Fecha de Finalización",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Si la función sustantiva está actualmente vigente",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_carga",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Carga"
                    ),
                ),
                (
                    "ultima_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "asignatura_vinculada",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si es docencia en otra asignatura, especificarla aquí",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_docentes_vinculadas",
                        to="planta_docente.asignatura",
                        verbose_name="Asignatura Vinculada",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_sustantivas",
                        to="planta_docente.cargo",
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "resolucion_cd",
                    models.ForeignKey(
                        help_text="Resolución CD de llamado a concurso que incluye esta función",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_sustantivas_establecidas",
                        to="planta_docente.resolucion",
                        verbose_name="Resolución de Consejo Directivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad Sustantiva",
                "verbose_name_plural": "Actividades Sustantivas",
                "ordering": ["-activa", "categoria", "fecha_inicio"],
                "indexes": [
                    models.Index(
                        fields=["cargo", "activa"], name="actsust_cargo_act_idx"
                    ),
                    models.Index(
                        fields=["categoria", "tipo_actividad"],
                        name="actsust_cat_tipo_idx",
                    ),
                    models.Index(
                        fields=["asignatura_vinculada"], name="actsust_asig_idx"
                    ),
                    models.Index(fields=["resolucion_cd"], name="actsust_resol_idx"),
                ],
            },
        ),
    ]
