# Generated by Django 5.2.7 on 2025-11-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0013_actividadsustantiva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadsustantiva",
            name="resolucion_cd",
            field=models.ForeignKey(
                blank=True,
                help_text="Resolución CD de llamado a concurso que incluye esta función",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actividades_sustantivas_establecidas",
                to="planta_docente.resolucion",
                verbose_name="Resolución de Consejo Directivo",
            ),
        ),
    ]
