# Generated by Django 5.2.7 on 2025-12-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0014_make_resolucion_cd_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="competencias",
            field=models.CharField(
                blank=True,
                help_text="Competencias específicas separadas por guiones (ej: CE01-CE03-CE08)",
                max_length=200,
                verbose_name="Competencias",
            ),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="contenidos_minimos",
            field=models.TextField(
                blank=True,
                help_text="Contenidos mínimos de la asignatura",
                verbose_name="Contenidos Mínimos",
            ),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="numero_orden",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Número de orden en el plan de estudios (ej: 16)",
                null=True,
                verbose_name="Número de Orden",
            ),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="objetivos",
            field=models.TextField(
                blank=True,
                help_text="Objetivos de la asignatura (uno por línea)",
                verbose_name="Objetivos",
            ),
        ),
    ]
