# Generated by Django 5.2.7 on 2025-12-12 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0015_asignatura_competencias_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanificacionAnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "año",
                    models.PositiveIntegerField(
                        help_text="Año para el cual es válida esta planificación",
                        verbose_name="Año lectivo",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        help_text="Formatos permitidos: PDF, DOCX (máx. 20MB)",
                        upload_to="planificaciones/%Y/",
                        verbose_name="Archivo de planificación",
                    ),
                ),
                (
                    "archivo_nombre_original",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Nombre original del archivo",
                    ),
                ),
                (
                    "fecha_subida",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de subida"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de recepción"),
                            ("enviada", "Notificación enviada"),
                            ("recibida", "Planificación recibida"),
                            ("aprobada", "Aprobada"),
                            ("observada", "Con observaciones"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "fecha_aprobacion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de aprobación"
                    ),
                ),
                (
                    "fecha_ultima_notificacion",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Última notificación enviada",
                    ),
                ),
                (
                    "cantidad_notificaciones",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cantidad de notificaciones enviadas"
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planificaciones_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planificaciones",
                        to="planta_docente.asignatura",
                        verbose_name="Asignatura",
                    ),
                ),
                (
                    "docente_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planificaciones_responsable",
                        to="planta_docente.docente",
                        verbose_name="Docente responsable",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planificaciones_subidas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Subido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planificación Anual",
                "verbose_name_plural": "Planificaciones Anuales",
                "db_table": "planta_docente_planificacion_anual",
                "ordering": ["-año", "asignatura__nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistorialNotificacionPlanificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_destinatario",
                    models.EmailField(
                        max_length=254, verbose_name="Email destinatario"
                    ),
                ),
                ("asunto", models.CharField(max_length=255, verbose_name="Asunto")),
                ("cuerpo", models.TextField(verbose_name="Cuerpo del mensaje")),
                (
                    "tipo_mensaje",
                    models.CharField(
                        choices=[
                            ("generico", "Mensaje genérico"),
                            ("personalizado", "Mensaje personalizado"),
                            ("recordatorio", "Recordatorio"),
                        ],
                        default="generico",
                        max_length=20,
                        verbose_name="Tipo de mensaje",
                    ),
                ),
                (
                    "archivos_adjuntos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de rutas de archivos adjuntados",
                        verbose_name="Archivos adjuntos",
                    ),
                ),
                (
                    "ficha_adjunta",
                    models.BooleanField(
                        default=False, verbose_name="Ficha de asignatura adjunta"
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de envío"
                    ),
                ),
                (
                    "enviado_exitosamente",
                    models.BooleanField(
                        default=False, verbose_name="Enviado exitosamente"
                    ),
                ),
                (
                    "error_envio",
                    models.TextField(blank=True, verbose_name="Error de envío"),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="planta_docente.docente",
                        verbose_name="Docente destinatario",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
                (
                    "planificacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_notificaciones",
                        to="planta_docente.planificacionanual",
                        verbose_name="Planificación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Notificación",
                "verbose_name_plural": "Historial de Notificaciones",
                "db_table": "planta_docente_historial_notificacion",
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.AddIndex(
            model_name="planificacionanual",
            index=models.Index(
                fields=["año", "estado"], name="planta_doce_año_5657fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planificacionanual",
            index=models.Index(
                fields=["asignatura", "año"], name="planta_doce_asignat_3a628d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="planificacionanual",
            unique_together={("asignatura", "año")},
        ),
        migrations.AddIndex(
            model_name="historialnotificacionplanificacion",
            index=models.Index(
                fields=["planificacion", "-fecha_envio"],
                name="planta_doce_planifi_00a6ac_idx",
            ),
        ),
    ]
