# Generated by Django 5.2.7 on 2025-12-15 17:17

import planta_docente.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0016_planificacionanual_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planificacionanual",
            name="archivo",
            field=models.FileField(
                help_text="Formatos permitidos: PDF, DOCX (máx. 20MB)",
                upload_to="planificaciones/%Y/",
                validators=[
                    planta_docente.validators.validar_extension_planificacion,
                    planta_docente.validators.validar_tamaño_planificacion,
                ],
                verbose_name="Archivo de planificación",
            ),
        ),
    ]
