# Generated by Django 5.2.7 on 2026-02-02 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0017_alter_planificacionanual_archivo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AsignaturaAnual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.PositiveIntegerField(verbose_name="Año lectivo")),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar si la asignatura no se dicta este año",
                        verbose_name="Asignatura activa este año",
                    ),
                ),
                (
                    "motivo_deshabilitacion",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Plan de estudios discontinuado, asignatura fusionada, etc.",
                        max_length=200,
                        verbose_name="Motivo de deshabilitación",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificación"
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_anual",
                        to="planta_docente.asignatura",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración Anual de Asignatura",
                "verbose_name_plural": "Configuraciones Anuales de Asignaturas",
                "db_table": "planta_docente_asignatura_anual",
                "ordering": ["-año", "asignatura__nombre"],
                "indexes": [
                    models.Index(
                        fields=["año", "activa"], name="planta_doce_año_daa1f1_idx"
                    ),
                    models.Index(
                        fields=["asignatura", "año"],
                        name="planta_doce_asignat_5df8f9_idx",
                    ),
                ],
                "unique_together": {("asignatura", "año")},
            },
        ),
    ]
