# Generated by Django 5.2.7 on 2026-02-05 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0018_asignaturaanual"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="es_responsable_planificacion",
            field=models.BooleanField(
                default=False,
                help_text="Marca este cargo como responsable de recibir notificaciones de planificación",
            ),
        ),
        migrations.AddConstraint(
            model_name="cargo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("es_responsable_planificacion", True)),
                fields=("asignatura",),
                name="unique_responsable_planificacion_por_asignatura_año",
            ),
        ),
    ]
