# Generated by Django 5.2.7 on 2026-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0019_cargo_es_responsable_planificacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="bibliografia_basica",
            field=models.TextField(
                blank=True,
                help_text="Bibliografía obligatoria de la asignatura (un título por línea)",
                verbose_name="Bibliografía Básica",
            ),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="bibliografia_complementaria",
            field=models.TextField(
                blank=True,
                help_text="Bibliografía de consulta adicional (un título por línea)",
                verbose_name="Bibliografía Complementaria",
            ),
        ),
    ]
