# Generated by Django 5.2.7 on 2026-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0020_asignatura_bibliografia_basica_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignatura",
            name="bibliografia_basica",
            field=models.TextField(
                blank=True,
                help_text='Formato IEEE. Ejemplo: [1] A. Autor, "Título del libro", Editorial, Año. (un ítem por línea)',
                verbose_name="Bibliografía Básica",
            ),
        ),
        migrations.AlterField(
            model_name="asignatura",
            name="bibliografia_complementaria",
            field=models.TextField(
                blank=True,
                help_text='Formato IEEE. Ejemplo: [1] A. Autor, "Título del libro", Editorial, Año. (un ítem por línea)',
                verbose_name="Bibliografía Complementaria",
            ),
        ),
    ]
