# Generated by Django 5.2.7 on 2026-04-10 15:47

import planta_docente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0021_agregar_bibliografia_asignatura"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="programa",
            field=models.FileField(
                blank=True,
                help_text="Archivo PDF del programa de la asignatura",
                null=True,
                upload_to=planta_docente.models.get_programa_upload_path,
                verbose_name="Programa",
            ),
        ),
    ]
