# Generated by Django 5.2.7 on 2026-04-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0022_asignatura_programa"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="cantidad_dedicaciones",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Cantidad de dedicaciones de este tipo. Ej: 2 DS = 2 unidades",
                verbose_name="Cantidad de Dedicaciones",
            ),
        ),
    ]
