# Generated by Django 5.2.7 on 2026-04-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0023_cargo_cantidad_dedicaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("asignatura", "Asignatura"),
                    ("laboratorio", "Laboratorio"),
                    ("area", "Área"),
                ],
                default="asignatura",
                max_length=11,
                verbose_name="Tipo",
            ),
        ),
    ]
