# Generated by Django 5.2.7 on 2026-04-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0024_asignatura_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asignatura",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("asignatura", "Asignatura"),
                    ("laboratorio", "Laboratorio"),
                    ("grupo", "Grupo"),
                    ("centro", "Centro"),
                    ("area", "Área"),
                ],
                default="asignatura",
                max_length=11,
                verbose_name="Tipo",
            ),
        ),
    ]
