# Generated by Django 4.2.30 on 2026-04-28 19:24

from django.db import migrations, models
import planta_docente.validators


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0025_alter_asignatura_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planificacionanual",
            name="archivo",
            field=models.FileField(
                help_text="Formatos permitidos: PDF, DOCX (máx. 20MB)",
                upload_to="private/planificaciones/%Y/",
                validators=[
                    planta_docente.validators.validar_extension_planificacion,
                    planta_docente.validators.validar_tamaño_planificacion,
                ],
                verbose_name="Archivo de planificación",
            ),
        ),
        migrations.AlterField(
            model_name="resolucion",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="private/resoluciones/"
            ),
        ),
    ]
