# Generated by Django 4.2.30 on 2026-08-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planta_docente", "0026_alter_planificacionanual_archivo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolucion",
            name="fecha",
            field=models.DateField(
                blank=True,
                help_text="Fecha exacta de la resolución. Registros viejos pueden no tenerla cargada.",
                null=True,
                verbose_name="Fecha de la Resolución",
            ),
        ),
    ]
